forDev/board/urls.py
from django.urls import path
from .views.base_views import *
from .views import base_views

app_name = "board"

urlpatterns = [
    # Create Test Case
    # path("test/", base_views.test, name="test"),
    path("api/", IndexView.as_view()),
    path("api/<int:id>", ContentView.as_view()),
    path("", base_views.index, name="index"),
    path("insert/", base_views.insert_board, name="insert"),
]

forDev/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),  # 글 작성
    path("user/", include("user.urls")),  # 로그인, 로그아웃, 정보수정
    # 팔로우
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forDev/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import *

# NameSpace 지정
app_name = "user"

urlpatterns = [
    # django.contrib.auth 에서 제공하는 로그인 View 클래스 호출
    # 기본 호출 경로 : registeration/login.html ==> template_name 별도 지정 필요
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="user/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
    path("mypage/", views.mypage, name="mypage"),
    path("register/", RegisterView.as_view()),
    path("login_token/", LoginView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forDev/board/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Board(models.Model):
    title = models.CharField(max_length=256)
    writer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="write_board"
    )
    created = models.DateTimeField(auto_now_add=True)
    content = models.JSONField()
    like = models.ManyToManyField(
        User, related_name="like_board", blank=True, null=True
    )
    tags = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self) -> str:
        return self.title + " / " + self.writer.username

forDev/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    profile = models.CharField(max_length=256)
    image = models.FileField(
        upload_to="profile/%Y/%M/%D", default="profile/default.png"
    )


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

forDev/board/forms.py
from django import forms
from .models import Board


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ["title", "content", "writer"]

forDev/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    profile = forms.CharField(label="인사말")
    image = forms.FileField()

    class Meta:
        model = User
        fields = ("username", "email")

forDev/board/views/base_views.py
from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
import json

from ..models import Board
from ..paginations import MyCursorPagination
from ..serializers import BoardContentSerializer, BoardSerializer, TagsSerializer

# from rest_pandas import PandasView


# class BoardDFVIew(PandasView):
#     board = Board.objects.all()

#     queryset = board
#     serializer_class = BoardSerializer
#     pagination_class = MyCursorPagination
#     # get()에 대한 응답으로 기본 Django REST Framework ListAPIView
#     # 는 기본 쿼리 세트(self.model.objects.all())를 로드한 다음
#     # 다음 함수에 전달합니다.
#     def filter_queryset(self, queryset):
#         # 이 시점에서 self.request 또는 다른
#         # 설정(메모리 사용을 제한하는 데 유용)을 기반으로 쿼리 집합을 필터링할 수 있습니다.
#         return queryset

#     # 그러면 포함된 PandasSerializer가 쿼리 세트를
#     # 간단한 사전 목록 목록으로 직렬화합니다(DRF ModelSerializer 사용). 포함할 # 필드 를 사용자 정의하려면
#     # PandasSerializer를 서브클래스로 만들고
#     # 적절한 ModelSerializer 옵션을 설정하십시오. 그런 다음 보기의 serializer_class
#     # 속성을 PandasSerializer 하위 클래스로 설정합니다.

#     # 다음으로 PandasSerializer는 ModelSerializer 결과를 DataFrame에 로드
#     # 하고 뷰의 다음 함수에 전달합니다.

#     def transform_dataframe(self, dataframe):
#         # 여기에서 self.request를 기반으로 데이터 프레임을 변환할 수 있습니다 .
#         # (피봇팅 또는 통계 계산에 유용함)
#         return dataframe

#     # 마지막으로 포함된 렌더러는 데이터 프레임을
#     # 아래의 출력 형식 중 하나로 처리합니다.


class IndexView(generics.ListAPIView):
    board = Board.objects.all()

    queryset = board
    serializer_class = BoardSerializer
    pagination_class = MyCursorPagination


class ContentView(APIView):
    def get(self, request, id):
        board = get_object_or_404(Board, pk=id)
        serializer = BoardContentSerializer(board)
        return Response(serializer.data, status=status.HTTP_200_OK)


@login_required(login_url="user:login")
def index(request):
    return render(request, "board/index.html")


def insert_board(request):
    if request.method == "POST":
        board = Board()
        board.title = request.POST.get("title")
        board.content = {"ops": json.loads(request.POST.get("content"))}
        board.writer = request.user
        board.tags = request.POST.get("tags")
        board.save()
    return redirect("board:index")


class ContentView(APIView):
    def get(self, request, id):
        board = get_object_or_404(Board, pk=id)
        serializer = BoardContentSerializer(board)
        return Response(serializer.data, status=status.HTTP_200_OK)


# def test(request):
#     for i in range(100):
#         test_board = Board()
#         test_board.title = f"This Is TestCase [{i + 1}]"
#         test_board.content = {
#             "ops": [
#                 {"insert": "Gandalf", "attributes": {"bold": "true"}},
#                 {"insert": " the "},
#                 {"insert": "Grey", "attributes": {"color": "#cccccc"}},
#             ]
#         }
#         test_board.writer = request.user
#         test_board.save()

forDev/user/views.py
from django.shortcuts import redirect, render
from .forms import UserForm
from .models import Profile
from .serializers import LoginSerializer, ProfileSerializer, RegisterSerializer
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from rest_framework import generics, status
from rest_framework.response import Response

# Create your views here.


class RegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = RegisterSerializer


class LoginView(generics.GenericAPIView):
    serializer_class = LoginSerializer

    @csrf_exempt
    def post(self, request):
        user_id = request.POST.get("username")
        user_pw = request.POST.get("password")

        user = authenticate(request, username=user_id, password=user_pw)

        if user is not None:
            login(request, user)

        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        token = serializer.validated_data
        return Response({"token": token.key}, status=status.HTTP_200_OK)


class ProfileView(generics.RetrieveUpdateAPIView):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer


# 회원가입 Form 보여주기
def signup(request):
    form = UserForm()
    return render(request, "user/signup.html", {"form": form})


def mypage(request):
    if request.method == "POST":
        print(request.POST.get["image"])
        form = UserForm(request.POST, instance=request.user)
        form.email = request.POST["email"]
        form.profile = request.POST["profile"]
        form.image = request.FILES["image"]
        form.save()
        return redirect("board:index")
    else:
        return render(request, "user/mypage.html")

forDev/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" />
    <title>forDev - 개발자를 위한 정보게시판</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block style %}{% endblock %}
  </head>
  <body>
    <!-- navbar -->
    {% include "navbar.html" %}
    <!-- Content -->
    {% block content %} {% endblock %}
    <!-- Modal -->
    {% block modal %}{% endblock %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block script %} {% endblock %}
  </body>
</html>

forDev/templates/board/index.html
{% extends 'base.html' %} {% load static %}
<!-- style -->
{% block style %}
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<link href="{% static 'css/quill.snow.css' %}" rel="stylesheet" />
{% endblock %}

<!-- Content 시작 -->
{% block content %}
<div class="content accordion" id="bbs"></div>
<div class="card side-btn">
  <div class="card-body">
    <div class="btn-row">
      <button type="button" class="btn btn-outline-primary m-2 btn-block side-menu show-editor">New</button>
    </div>
    <div class="btn-row">
      <a class="btn btn-outline-primary m-2 btn-block side-menu" href="#">Top</a>
    </div>
  </div>
</div>
<form action="{% url 'board:insert' %}" method="post" id="boardInsertForm">
  {% csrf_token %}
  <input type="hidden" name="title" id="boardTitle" />
  <input type="hidden" name="content" id="boardContent" />
  <input type="hidden" name="tags" id="boardTags" />
</form>
<!-- Spinner 로딩 표시 -->
<div class="d-flex justify-content-center">
  <div class="spinner-grow text-warning" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>
{% endblock %} {% block script %}

<script src="{% static 'js/quill.js' %}"></script>
<script src="{% static 'js/Chart.min.js' %}"></script>
<script src="{% static 'js/d3.v3.min.js' %}"></script>
<script src="{% static 'js/d3.layout.cloud.js' %}" type="text/JavaScript"></script>
<script src="{% static 'js/infinite-scroll.js' %}"></script>

<script>
  // Quill Toolbar Option
  var toolbarOptions = [
    ['bold', 'italic', 'underline', 'strike', 'code'],        // toggled buttons

    [{ 'header': 1 }, { 'header': 2 }],               // custom button values
    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
    [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
    [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent

    [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown

    [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
    [{ 'align': [] }],

    ['clean']                                         // remove formatting button
  ];

  // Quill Editor 선언
  var quill = new Quill('#editor', {
    modules: {
      toolbar: toolbarOptions
    },
    placeholder: '"</>" 속성으로 블록을 지정하면, 태그로 등록이 됩니다...',
    theme: 'snow'
  });

  // Loading 스피너
  let spinner = document.getElementById('spinner');

  // 스크롤 구현
  let id = "";
  $(function () {
    let content = $(".content");
    var $win = $(window);
    // 최초 페이지 로딩 시 1회 실행
    $.getJSON({
      url: "/board/api/" + id.substring(id.indexOf("?")),
      success: function (result) {
        if(result.next){
          id = result.next;
        }else{
          return;
        }
        let tagList = getTagCount(result);
        content.append(scrollData(result));
        drawBarChart(result, tagList)
        // drawWordCloud(result, tagList)
        drawWordCloud(result, tagList)
      },
    });

    // 스크롤 이후 동작
    $win.scroll(
      debounce(function () {

        var diff = $(document).height() - $win.height() - 50;
        if (diff < $win.scrollTop()) {
          $.getJSON({
            url: "/board/api/" + id.substring(id.indexOf("?")),
            success: function (result) {
              if(result.next){
                id = result.next;
              }else{
                return;
              }
              let tagList = getTagCount(result);
              content.append(scrollData(result));
              drawBarChart(result, tagList);
              drawWordCloud(result, tagList);
            },
          });
        }
      }, 1500)
    );

    $(".show-editor").click(function(e){
      quill.setContents();
      $("#staticBackdrop").modal("show");
    })

    $(".board-insert").click(function(e){
      e.preventDefault();

      content = quill.getContents()
      $("#boardTitle").val($("#title").val());
      let tags = "";
      var flag = false;
      content.ops.forEach(element => {
        if(element.attributes){
          if(element.attributes.code){
            tags += "#" + element.insert;
            element.insert = "<# " + element.insert + " >"
            if(tags.length >= 120){
              alert("태그가 너무 많습니다.")
              flag = true;
            }
          }
        }
      })
      if(flag){
        return;
      }
      $("#boardContent").val(JSON.stringify(content.ops));
      $("#boardTags").val(tags)
      $("#boardInsertForm").submit();
    })


  });

  // 추천버튼 Click
  function recommend(boardId){
    console.log(boardId)
  }

  const scrollData = (result) => {
    str = '';
    // 태그 분석 부분
    str +=
      '<div class="d-flex justify-content-center text-center tags-analyze">'+
        '<div class="m-2">'+
          '<canvas id="bar-chart-' + result.next.substring(result.next.indexOf("=") + 1) + '" width="450" height="250"></canvas>'+
        '</div>'+
        '<div class="m-2">'+
          '<svg id="wordcloud-' + result.next.substring(result.next.indexOf("=") + 1) + '" class="wordcloud" width="450" height="250">'+
        '</div>'+
      '</div>'+
      '<hr />'
    ;

    str += '<div class="container">';

    // 게시판 내용 부분
    result.results.forEach((currentElement, index, array) => {
      tags = "";
      if(currentElement.tags){
        for(tag of currentElement.tags){
          tags += "#" + tag + " "
        }
      }
      str +=
        '<div id="heading-' + currentElement.id + '">'+
          '<h2 class="mb-0">'+
            '<button class="btn btn-block text-left bbs" type="button" data-toggle="collapse" data-target="#collapse-' + currentElement.id + '" aria-expanded="true" aria-controls="collapse-' + currentElement.id + '" onclick="getContent(' + currentElement.id + ')">'+
              '<div class="media">'+
                '<img src="' + currentElement.writer.profile.image + '" class="mr-3 profile-img" width="75em" height="75em" />'+
                '<div class="media-body">'+
                  '<div class="row">'+
                    '<p class="col-lg-2">LIKE <span class="badge badge-pill badge-primary">' + currentElement.like.length + '</span></p>'+
                    '<h5 class="col-lg-8 mt-0 font-weight-bolder">' + currentElement.title + '</h5>'+
                    '<p class="col-lg-2 text-center font-weight-bolder">' + currentElement.writer.username + '</p>'+
                  '</div>'+
                  '<div class="row">'+
                    '<p class="col-lg-6 font-weight-lighter">' + tags +'</p>'+
                    '<p class="col-lg-4">' + getYmd10(new Date(currentElement.created)) + '</p>'+
                  '</div>'+
                '</div>'+
              '</div>'+
            '</button>'+
          '</h2>'+
        '</div>'+
        '<div id="collapse-' + currentElement.id + '" class="collapse" aria-labelledby="heading-' + currentElement.id + '" data-parent="#bbs">'+
          '<div class="d-flex justify-content-right">'+
            '<button type="button" class="btn btn-primary btn-xs m-2" onclick="recommend(' + currentElement.id + ')">추천</button>'+
            '<button type="button" class="btn btn-primary btn-xs m-2">작성자 정보</button>'+
          '</div>'+
          '<div class="ql-editor quill-content-' + currentElement.id + ' quill-content"></div>'+
        '</div>'
      ;
    });
    str += '</div>';
    return str;
  }

  var color = d3.scale.linear()
          .domain([0,1,2,3,4,5,6,10,15,20,100])
          .range(["#d33", "#c44", "#b11", "#a93", "#389", "#81f", "#73f", "#6f6", "#055", "#434", "#533", "#292"]);
  function drawWordCloud(result, tagList){
    console.log(tagList)
    let data = new Array();
    for (let [key, value] of Object.entries(tagList)) {
      var obj = new Object();
      obj.text = key;
      obj.value = value;

      data.push(obj);
    }
    console.log(data)

    d3.layout.cloud().size([450, 250])
            .words(data)
            .padding(0.2)
            .rotate(function () {
              return ~~(Math.random() * 2) * 90;
            })
            .fontSize(function(d) { return (d.value + 30 * 2) / 2; })
            .on("end", draw)
            .start();
  }

  function draw(words, pos) {
      console.log(words)
      console.log(pos)
      console.log(id) 
      d3.select("#wordcloud-" + id.substring(id.indexOf("=") + 1)).append("g")
        // without the transform, words words would get cutoff to the left and top, they would
        // appear outside of the SVG area
        .attr("transform", "translate(250,150)")
        .selectAll("text")
        .data(words)
        .enter().append("text")
        .style("font-size", function(d) { return (d.size) + "px"; })
        .style('font-family', 'Impact')
        .style("fill", function(d, i) { return color(i); })
        .attr("text-anchor", "middle")
        .attr("transform", (d) => "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")")
        .text(function(d) { return d.text; });
  }

  //yyyy-mm-dd 포맷 날짜 생성
  function getYmd10(d) {
    return d.getFullYear() + "-" + ((d.getMonth() + 1) > 9 ? (d.getMonth() + 1).toString() : "0" + (d.getMonth() + 1)) + "-" + (d.getDate() > 9 ? d.getDate().toString() : "0" + d.getDate().toString());
  }
</script>

{% endblock %}
<!-- Modal -->
{% block modal %}
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title ml-3" id="staticBackdropLabel">New Board</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="title" class="modal-title ml-3"><h5>Title</h5></label>
          <input type="text" name="title" id="title" class="form-control" />
        </div>
        <hr />
        <div id="editor"></div>
        <hr />

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary board-insert">save</button>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

forDev/templates/form_errors.html
<!-- 오류표시 -->
{% if form.errors %}
<!--  -->
{% for field in form %}
<!-- form 안의 요소들 오류 출력 : 입력값 누락, 형식에 맞지 않는 경우 -->
{% for error in field.errors %}
<div class="alert alert-danger" role="alert">
  <strong>{{field.label}}</strong>
  {{ error }}
</div>
{% endfor %} {% endfor %}
<!-- non_field_errors : 입력값과 관계없이 발생한 오류 -->
{% for error in field.non_field_errors %}
<div class="alert alert-danger" role="alert">
  <strong>{{ error }}</strong>
</div>
{% endfor %} {% endif %}

forDev/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand ml-5" href="{% url 'board:index' %}">
    <img src="{% static 'img/Logo.png' %}" class="d-inline-block align-top" alt="" width="160" height="50" />
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse m-5 d-flex justify-content-between" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item mr-5">
        <a class="nav-link" href="#">My Board</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Uncompleted</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        {% if user.is_authenticated %}
        <div class="dropdown">
          <a class="nav-link dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'user:mypage' %}">My Page</a>
            <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
          </div>
        </div>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>

forDev/templates/user/login.html
{% extends 'base.html' %} {% load static %}

<!-- Content -->
{% block content %}
<div class="content d-flex justify-content-center">
  <hr />
  <div class="user-box">
    <div class="user-header text-center">
      <h2><b>Login</b></h2>
    </div>
    <form action="" method="post" id="userForm">
      {% csrf_token %}
      <div class="form-group m-4">{% include 'form_errors.html' %}</div>
      <div class="form-group m-4">
        <label for="username"><b>ID</b></label>
        <input type="text" name="username" id="username" class="form-control" />
      </div>
      <div class="form-group m-4">
        <label for="password"><b>Password</b></label>
        <input type="password" name="password" id="password" class="form-control" />
      </div>
      <div class="form-group m-4">
        <button type="submit" class="btn btn-outline-primary btn-sm btn-block login">Login</button>
        <p class="d-flex justify-content-between m-1">
          <a href="{% url 'user:signup' %}" class="text-decoration-none">회원가입</a>
          <a href="#" class="text-decoration-none">아이디/비밀번호 찾기</a>
        </p>
      </div>
    </form>
  </div>
</div>
{% endblock %} {% block script %}

<script>
  $(function () {
    $(".login").click(function (e) {
      e.preventDefault();
      $.ajax({
        url: "/user/login_token/",
        type: "post",
        data: {
          username: $("#username").val(),
          password: $("#password").val(),
        },
        dataType: "json",
        success: function (result) {
          console.log(result);
          location.href = "/board/";
        },
        error: function () {},
      });
    });
  });
</script>
{% endblock %}

forDev/templates/user/mypage.html
{% extends 'base.html' %} {% load static %}

<!-- Content -->
{% block content %}
<div class="content d-flex justify-content-center">
  <hr />
  <div class="user-box">
    <div class="user-header text-center">
      <h2><b>MyPage</b></h2>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group m-4">{% include 'form_errors.html' %}</div>
      <div class="form-group m-4">
        <label for="username"><b>ID</b></label>
        <input type="text" class="form-control" name="username" id="username" value="{{ user.username }}" readonly />
      </div>
      <div class="form-group m-4">
        <label for="password1"><b>Password</b></label>
        <input type="password" name="password1" id="password1" class="form-control" placeholder="PASSOWRD" />
      </div>
      <div class="form-group m-4">
        <label for="password2"><b>Password Check</b></label>
        <input type="password" name="password2" id="password2" class="form-control" placeholder="PASSOWRD CHECK" />
      </div>
      <div class="form-group m-4">
        <label for="email"><b>Email</b></label>
        <input type="email" name="email" id="email" class="form-control" value="{{ user.email }}" />
      </div>
      <div class="form-group m-4">
        <label for="profile"><b>Profile</b></label>
        <textarea name="profile" id="profile" rows="5" class="form-control" style="resize: none">{{ user.profile.profile }}</textarea>
      </div>
      <div class="form-group m-4">
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="image" aria-describedby="image" />
          <label class="custom-file-label" for="image">{{ user.profile.image }}</label>
        </div>
      </div>
      <div class="form-group m-4">
        <button type="submit" class="btn btn-outline-primary btn-sm btn-block">Update</button>
      </div>
    </form>
  </div>
</div>
{% endblock %} {% block script %}
<script>
  $(function () {
    $("#image").change(function () {
      $(".custom-file").find("label").text($("#image").val());
    });
  });
</script>
{% endblock %}

forDev/templates/user/signup.html
{% extends 'base.html' %} {% load static %}

<!-- Content -->
{% block content %}
<div class="content d-flex justify-content-center">
  <hr />
  <div class="user-box">
    <div class="user-header text-center">
      <h2><b>SignUp</b></h2>
    </div>
    <form action="" method="post" id="userForm">
      {% csrf_token %}
      <div class="form-group m-4">{% include 'form_errors.html' %}</div>
      <div class="form-group m-4">
        <label for="username"><b>ID</b></label>
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="ID" aria-describedby="button-addon2" name="username" id="username" value="{{ form.username.value | default_if_none:''}}" />
          <div class="input-group-append">
            <button class="btn btn-outline-info" style="z-index: 0" type="button" id="button-addon2">중복체크</button>
          </div>
        </div>
      </div>
      <div class="form-group m-4">
        <label for="password1"><b>Password</b></label>
        <input type="password" name="password1" id="password1" class="form-control" placeholder="PASSOWRD" />
      </div>
      <div class="form-group m-4">
        <label for="password2"><b>Password Check</b></label>
        <input type="password" name="password2" id="password2" class="form-control" placeholder="PASSOWRD CHECK" />
      </div>
      <div class="form-group m-4">
        <label for="email"><b>Email</b></label>
        <input type="email" name="email" id="email" class="form-control" placeholder="example@example.com" value="{{ form.email.value | default_if_none:''}}" />
      </div>
      <div class="form-group m-4">
        <button type="submit" class="btn btn-outline-primary btn-sm btn-block signup">SignUp</button>
      </div>
    </form>
  </div>
</div>
{% endblock %} {% block script %}
<script>
  $(function () {
    $(".signup").click(function (e) {
      e.preventDefault();
      $.ajax({
        url: "/user/register/",
        type: "post",
        data: {
          username: $("#username").val(),
          password: $("#password1").val(),
          password2: $("#password2").val(),
          email: $("#email").val(),
        },
        dataType: "json",
        success: function (result) {
          alert("성공적으로 가입되었습니다.");
          location.href = "/board/";
        },
        error: function (fqXHR, error) {
          console.log(error);
        },
      });
    });
  });
</script>
{% endblock %}